project_name: '@pulumi/gotiac'

archives:
    - id: archive
      name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'

monorepo:
    tag_prefix: '@pulumi/gotiac/'
    dir: packages/pulumi-gotiac-aws

before:
    hooks:
        - make build_provider
builds:
    - binary: pulumi-resource-gotiac
      dir: provider
      env:
          - CGO_ENABLED=0
      goarch:
          - amd64
          - arm64
      goos:
          - darwin
          - windows
          - linux
      ldflags:
          # The line below MUST align with the module in current provider/go.mod
          - -X github.com/gothub-team/got/packages/pulumi-gotiac-aws/provider.Version={{.Tag }}
      main: ./cmd/pulumi-resource-gotiac/
changelog:
    skip: true
release:
    disable: false
    prerelease: auto
snapshot:
    name_template: '{{ .Tag }}-SNAPSHOT'
