# yaml-language-server: $schema=https://raw.githubusercontent.com/pulumi/pulumi/master/pkg/codegen/schema/pulumi.json
---
name: gotiac
resources:
    gotiac:index:FileHosting:
        isComponent: true
        inputProperties:
            domain:
                type: string
                description: The file hosting domain.
            bucketName:
                type: string
                description:
                    The name of an existing s3 Bucket to link as origin. If not provided, a new bucket will be created.
        requiredInputs:
            - domain
        properties:
            url:
                type: string
                description: The file hosting URL.
            privateKeyParameterName:
                type: string
                description: The parameter name for the private key.
            privateKeyId:
                type: string
                description: The ID the private key.
        required:
            - url
            - privateKeyParameterName
            - privateKeyId
language:
    csharp:
        packageReferences:
            Pulumi: 3.*
            Pulumi.Aws: 4.*
    go:
        generateResourceContainerTypes: true
        importBasePath: github.com/pulumi/pulumi-gotiac/sdk/go/gotiac
    nodejs:
        dependencies:
            '@pulumi/aws': '^6.0.0'
        devDependencies:
            typescript: '*'
            '@types/node': '*'
    python:
        requires:
            pulumi: '>=3.0.0,<4.0.0'
            pulumi-aws: '>=4.0.0,<5.0.0'
