// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Api extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'gotiac:index:Api';

    /**
     * Returns true if the given object is an instance of Api.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Api {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Api.__pulumiType;
    }

    /**
     * The endpoint of the API.
     */
    public /*out*/ readonly endpoint!: pulumi.Output<string>;

    /**
     * Create a Api resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.codePath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'codePath'");
            }
            if ((!args || args.handlerPath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'handlerPath'");
            }
            if ((!args || args.policyArns === undefined) && !opts.urn) {
                throw new Error("Missing required property 'policyArns'");
            }
            if ((!args || args.routePath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'routePath'");
            }
            if ((!args || args.runtime === undefined) && !opts.urn) {
                throw new Error("Missing required property 'runtime'");
            }
            if ((!args || args.userPoolId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'userPoolId'");
            }
            resourceInputs["codePath"] = args ? args.codePath : undefined;
            resourceInputs["handlerPath"] = args ? args.handlerPath : undefined;
            resourceInputs["memorySize"] = args ? args.memorySize : undefined;
            resourceInputs["policyArns"] = args ? args.policyArns : undefined;
            resourceInputs["routePath"] = args ? args.routePath : undefined;
            resourceInputs["runtime"] = args ? args.runtime : undefined;
            resourceInputs["userPoolId"] = args ? args.userPoolId : undefined;
            resourceInputs["endpoint"] = undefined /*out*/;
        } else {
            resourceInputs["endpoint"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Api.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Api resource.
 */
export interface ApiArgs {
    /**
     * The path to a .zip file containing your deployment package.
     */
    codePath: pulumi.Input<string>;
    /**
     * The path to the handler in the deployment package.
     */
    handlerPath: pulumi.Input<string>;
    /**
     * The amount of memory in MB your Lambda Function can use at runtime.
     */
    memorySize?: pulumi.Input<number>;
    /**
     * The ARNs of the policies that are attached to the Lambda function.
     */
    policyArns: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The path to the route in the API.
     */
    routePath: pulumi.Input<string>;
    /**
     * The runtime environment for the Lambda function.
     */
    runtime: pulumi.Input<string>;
    /**
     * ID of the user pool.
     */
    userPoolId: pulumi.Input<string>;
}
