// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { FileHostingArgs } from "./fileHosting";
export type FileHosting = import("./fileHosting").FileHosting;
export const FileHosting: typeof import("./fileHosting").FileHosting = null as any;
utilities.lazyLoad(exports, ["FileHosting"], () => require("./fileHosting"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { TestAdminUserArgs } from "./testAdminUser";
export type TestAdminUser = import("./testAdminUser").TestAdminUser;
export const TestAdminUser: typeof import("./testAdminUser").TestAdminUser = null as any;
utilities.lazyLoad(exports, ["TestAdminUser"], () => require("./testAdminUser"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "gotiac:index:FileHosting":
                return new FileHosting(name, <any>undefined, { urn })
            case "gotiac:index:TestAdminUser":
                return new TestAdminUser(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("gotiac", "index", _module)
pulumi.runtime.registerResourcePackage("gotiac", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:gotiac") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
