// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Lambda extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'gotiac:index:Lambda';

    /**
     * Returns true if the given object is an instance of Lambda.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Lambda {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Lambda.__pulumiType;
    }

    /**
     * The ARN of the Lambda function.
     */
    public /*out*/ readonly arn!: pulumi.Output<string>;
    /**
     * The Name of the Lambda function.
     */
    public /*out*/ readonly name!: pulumi.Output<string>;

    /**
     * Create a Lambda resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: LambdaArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.codePath === undefined) && !opts.urn) {
                throw new Error("Missing required property 'codePath'");
            }
            if ((!args || args.handler === undefined) && !opts.urn) {
                throw new Error("Missing required property 'handler'");
            }
            if ((!args || args.policyArns === undefined) && !opts.urn) {
                throw new Error("Missing required property 'policyArns'");
            }
            if ((!args || args.runtime === undefined) && !opts.urn) {
                throw new Error("Missing required property 'runtime'");
            }
            resourceInputs["codePath"] = args ? args.codePath : undefined;
            resourceInputs["handler"] = args ? args.handler : undefined;
            resourceInputs["memorySize"] = args ? args.memorySize : undefined;
            resourceInputs["policyArns"] = args ? args.policyArns : undefined;
            resourceInputs["runtime"] = args ? args.runtime : undefined;
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
        } else {
            resourceInputs["arn"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Lambda.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a Lambda resource.
 */
export interface LambdaArgs {
    /**
     * The path to a .zip file containing your deployment package.
     */
    codePath: pulumi.Input<string>;
    /**
     * The path to the handler in the deployment package.
     */
    handler: pulumi.Input<string>;
    /**
     * The amount of memory in MB your Lambda Function can use at runtime.
     */
    memorySize?: pulumi.Input<number>;
    /**
     * The ARNs of the policies that are attached to the Lambda function.
     */
    policyArns: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The runtime environment for the Lambda function.
     */
    runtime: pulumi.Input<string>;
}
