// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class MailUser extends pulumi.ComponentResource {
    /** @internal */
    public static readonly __pulumiType = 'gotiac:index:MailUser';

    /**
     * Returns true if the given object is an instance of MailUser.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MailUser {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MailUser.__pulumiType;
    }

    /**
     * The ID of the organization that can be used to create mailboxes
     */
    public /*out*/ readonly userId!: pulumi.Output<string>;

    /**
     * Create a MailUser resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MailUserArgs, opts?: pulumi.ComponentResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if ((!args || args.displayName === undefined) && !opts.urn) {
                throw new Error("Missing required property 'displayName'");
            }
            if ((!args || args.emailPrefix === undefined) && !opts.urn) {
                throw new Error("Missing required property 'emailPrefix'");
            }
            if ((!args || args.name === undefined) && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if ((!args || args.region === undefined) && !opts.urn) {
                throw new Error("Missing required property 'region'");
            }
            resourceInputs["displayName"] = args ? args.displayName : undefined;
            resourceInputs["domain"] = args ? args.domain : undefined;
            resourceInputs["emailPrefix"] = args ? args.emailPrefix : undefined;
            resourceInputs["firstName"] = args ? args.firstName : undefined;
            resourceInputs["lastName"] = args ? args.lastName : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["organizationId"] = args ? args.organizationId : undefined;
            resourceInputs["region"] = args ? args.region : undefined;
            resourceInputs["userId"] = undefined /*out*/;
        } else {
            resourceInputs["userId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MailUser.__pulumiType, name, resourceInputs, opts, true /*remote*/);
    }
}

/**
 * The set of arguments for constructing a MailUser resource.
 */
export interface MailUserArgs {
    /**
     * The display name for the new user.
     */
    displayName: pulumi.Input<string>;
    /**
     * The mail domain of the organization for which the user is created. Either organizationId or domain must be specified.
     */
    domain?: pulumi.Input<string>;
    /**
     * The email prefix for the new user. (prefix@domain.com). The default domain of the organization will be appended automatically.
     */
    emailPrefix: pulumi.Input<string>;
    /**
     * The first name of the new user.
     */
    firstName?: pulumi.Input<string>;
    /**
     * The last name of the new user.
     */
    lastName?: pulumi.Input<string>;
    /**
     * The name for the new user. WorkMail directory user names have a maximum length of 64. All others have a maximum length of 20.
     */
    name: pulumi.Input<string>;
    /**
     * The identifier of the organization for which the user is created. Either organizationId or domain must be specified.
     */
    organizationId?: pulumi.Input<string>;
    /**
     * The region to create the mail domain in
     */
    region: pulumi.Input<string>;
}
