// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Gotiac
{
    [GotiacResourceType("gotiac:index:MailDomain")]
    public partial class MailDomain : global::Pulumi.ComponentResource
    {
        /// <summary>
        /// A random string to ensure uniqueness.
        /// </summary>
        [Output("random")]
        public Output<string> Random { get; private set; } = null!;


        /// <summary>
        /// Create a MailDomain resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public MailDomain(string name, MailDomainArgs? args = null, ComponentResourceOptions? options = null)
            : base("gotiac:index:MailDomain", name, args ?? new MailDomainArgs(), MakeResourceOptions(options, ""), remote: true)
        {
        }

        private static ComponentResourceOptions MakeResourceOptions(ComponentResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new ComponentResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/gothub-team/got/releases/download/packages/pulumi-gotiac-aws/v0.0.49",
            };
            var merged = ComponentResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
    }

    public sealed class MailDomainArgs : global::Pulumi.ResourceArgs
    {
        public MailDomainArgs()
        {
        }
        public static new MailDomainArgs Empty => new MailDomainArgs();
    }
}
