// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from '@pulumi/pulumi';
import * as inputs from '../types/input';
import * as outputs from '../types/output';

export interface ApiFileHostingInputArgs {
    /**
     * The name of the created media bucket that is used to store files.
     */
    bucketName: pulumi.Input<string>;
    /**
     * The file hosting domain.
     */
    domain: pulumi.Input<string>;
    /**
     * The ID of the private key which is used to identify which key was used to sign a URL.
     */
    privateKeyId: pulumi.Input<string>;
    /**
     * The ssm parameter name for the private key that is used to sign upload and download URLs.
     */
    privateKeyParameterName: pulumi.Input<string>;
}
