name: release-pulumi-gotiac-aws
on:
    push:
        tags:
            - 'packages/got-api/v*.*.*'
            - '!v*.*.*-**'
env:
    # THIS GITHUB_TOKEN IS A REQUIREMENT TO BE ABLE TO WRITE TO GH RELEASES
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # IF YOU NEED TO PUBLISH A NPM PACKAGE THEN ENSURE A NPM_TOKEN SECRET IS SET
    # AND PUBLISH_NPM: TRUE. IF YOU WANT TO PUBLISH TO A PRIVATE NPM REGISTRY
    # THEN ENSURE THE NPM_REGISTRY_URL IS CHANGED
    # NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    NPM_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
    PUBLISH_NPM: true
    NPM_REGISTRY_URL: https://registry.npmjs.org
jobs:
    publish:
        name: Publish SDKs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Unshallow clone for tags
              run: git fetch --tags --force
            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.nodeversion}}
                  registry-url: ${{env.NPM_REGISTRY_URL}}
            - name: Check worktree clean
              working-directory: ./packages/got-api
              run: |
                  git update-index -q --refresh
                  if ! git diff-files --quiet; then
                      >&2 echo "error: working tree is not clean, aborting!"
                      git status
                      git diff
                      exit 1
                  fi
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://registry.npmjs.org'
            - uses: JS-DevTools/npm-publish@v1
              with:
                  access: 'public'
                  token: ${{ env.NPM_TOKEN }}
                  package: ${{github.workspace}}/packages/got-api/package.json
        strategy:
            fail-fast: true
